//ALGORITMO PASAR PREGUNTAS/BARRA DE PROGRESO/BARRA DE PREGUNTAS
function mostrar(){

/*Función ready BOTONES
	pasa pregunta a pregunta por medio de los botones anterior/siguiente*/
	$(document).ready(function(){//acciona la función ready cuando el documento de carga
	$(".Preguntas").hide();//Oculta los contenedores div solo muestra el primero llamandolos por su class
	$("#sig").on('click',function(){//asigna función on click al botón por su id para accionarla
		$("#Preguntas1").next().show();//muestra el contenedor siguiente al actual llamandolo por la id del actual
		$("#Preguntas1").hide();//oculta el contenedor actual por su id
	});//fin función on click
	$("#sig2").on('click',function(){
		$("#Preguntas2").next().show();
		$("#Preguntas2").hide();
	});
	$("#ant").on('click',function(){
		$("#Preguntas2").prev().show();
		$("#Preguntas2").hide();
	});
	$("#sig3").on('click',function(){
		$("#Preguntas3").next().show();
		$("#Preguntas3").hide();
	});
	$("#ant2").on('click',function(){
		$("#Preguntas3").prev().show();
		$("#Preguntas3").hide();
	});
	$("#sig4").on('click',function(){
		$("#Preguntas4").next().show();
		$("#Preguntas4").hide();
	});
	$("#ant3").on('click',function(){
		$("#Preguntas4").prev().show();
		$("#Preguntas4").hide();
	});
	$("#sig5").on('click',function(){
		$("#Preguntas5").next().show();
		$("#Preguntas5").hide();
	});
	$("#ant4").on('click',function(){
		$("#Preguntas5").prev().show();
		$("#Preguntas5").hide();
	});
	$("#sig6").on('click',function(){
		$("#Preguntas6").next().show();
		$("#Preguntas6").hide();
	});
	$("#ant5").on('click',function(){
		$("#Preguntas6").prev().show();
		$("#Preguntas6").hide();
	});
	$("#sig7").on('click',function(){
		$("#Preguntas7").next().show();
		$("#Preguntas7").hide();
	});
	$("#ant6").on('click',function(){
		$("#Preguntas7").prev().show();
		$("#Preguntas7").hide();
	});
	$("#sig8").on('click',function(){
		$("#Preguntas8").next().show();
		$("#Preguntas8").hide();
	});
	$("#ant7").on('click',function(){
		$("#Preguntas8").prev().show();
		$("#Preguntas8").hide();
	});
	$("#sig9").on('click',function(){
		$("#Preguntas9").next().show();
		$("#Preguntas9").hide();
	});
	$("#ant8").on('click',function(){
		$("#Preguntas9").prev().show();
		$("#Preguntas9").hide();
	});
	$("#sig10").on('click',function(){
		$("#Preguntas10").next().show();
		$("#Preguntas10").hide();
	});
	$("#ant9").on('click',function(){
		$("#Preguntas10").prev().show();
		$("#Preguntas10").hide();
	});
	$("#sig11").on('click',function(){
		$("#Preguntas11").next().show();
		$("#Preguntas11").hide();
	});
	$("#ant10").on('click',function(){
		$("#Preguntas11").prev().show();
		$("#Preguntas11").hide();
	});
	$("#sig12").on('click',function(){
		$("#Preguntas12").next().show();
		$("#Preguntas12").hide();
	});
	$("#ant11").on('click',function(){
		$("#Preguntas12").prev().show();
		$("#Preguntas12").hide();
	});
	$("#sig13").on('click',function(){
		$("#Preguntas13").next().show();
		$("#Preguntas13").hide();
	});
	$("#ant12").on('click',function(){
		$("#Preguntas13").prev().show();
		$("#Preguntas13").hide();
	});
	$("#sig14").on('click',function(){
		$("#Preguntas14").next().show();
		$("#Preguntas14").hide();
	});
	$("#ant13").on('click',function(){
		$("#Preguntas14").prev().show();
		$("#Preguntas14").hide();
	});
	$("#sig15").on('click',function(){
		$("#Preguntas15").next().show();
		$("#Preguntas15").hide();
	});
	$("#ant14").on('click',function(){
		$("#Preguntas15").prev().show();
		$("#Preguntas15").hide();
	});
	$("#sig16").on('click',function(){
		$("#Preguntas16").next().show();
		$("#Preguntas16").hide();
	});
	$("#ant15").on('click',function(){
		$("#Preguntas16").prev().show();
		$("#Preguntas16").hide();
	});
	$("#sig17").on('click',function(){
		$("#Preguntas17").next().show();
		$("#Preguntas17").hide();
	});
	$("#ant16").on('click',function(){
		$("#Preguntas17").prev().show();
		$("#Preguntas17").hide();
	});
	$("#sig18").on('click',function(){
		$("#Preguntas18").next().show();
		$("#Preguntas18").hide();
	});
	$("#ant17").on('click',function(){
		$("#Preguntas18").prev().show();
		$("#Preguntas18").hide();
	});
	$("#sig19").on('click',function(){
		$("#Preguntas19").next().show();
		$("#Preguntas19").hide();
	});
	$("#ant18").on('click',function(){
		$("#Preguntas19").prev().show();
		$("#Preguntas19").hide();
	});
	$("#sig20").on('click',function(){
		$("#Preguntas20").next().show();
		$("#Preguntas20").hide();
	});
	$("#ant19").on('click',function(){
		$("#Preguntas20").prev().show();
		$("#Preguntas20").hide();
	});
	$("#sig21").on('click',function(){
		$("#Preguntas21").next().show();
		$("#Preguntas21").hide();
	});
	$("#ant20").on('click',function(){
		$("#Preguntas21").prev().show();
		$("#Preguntas21").hide();
	});
	$("#sig22").on('click',function(){
		$("#Preguntas22").next().show();
		$("#Preguntas22").hide();
	});
	$("#ant21").on('click',function(){
		$("#Preguntas22").prev().show();
		$("#Preguntas22").hide();
	});
	$("#sig23").on('click',function(){
		$("#Preguntas23").next().show();
		$("#Preguntas23").hide();
	});
	$("#ant22").on('click',function(){
		$("#Preguntas23").prev().show();
		$("#Preguntas23").hide();
	});
	$("#sig24").on('click',function(){
		$("#Preguntas24").next().show();
		$("#Preguntas24").hide();
	});
	$("#ant23").on('click',function(){
		$("#Preguntas24").prev().show();
		$("#Preguntas24").hide();
	});
	$("#sig25").on('click',function(){
		$("#Preguntas25").next().show();
		$("#Preguntas25").hide();
	});
	$("#ant24").on('click',function(){
		$("#Preguntas25").prev().show();
		$("#Preguntas25").hide();
	});
	$("#sig26").on('click',function(){
		$("#Preguntas26").next().show();
		$("#Preguntas26").hide();
	});
	$("#ant25").on('click',function(){
		$("#Preguntas26").prev().show();
		$("#Preguntas26").hide();
	});
	$("#sig27").on('click',function(){
		$("#Preguntas27").next().show();
		$("#Preguntas27").hide();
	});
	$("#ant26").on('click',function(){
		$("#Preguntas27").prev().show();
		$("#Preguntas27").hide();
	});
	$("#sig28").on('click',function(){
		$("#Preguntas28").next().show();
		$("#Preguntas28").hide();
	});
	$("#ant27").on('click',function(){
		$("#Preguntas28").prev().show();
		$("#Preguntas28").hide();
	});
	$("#sig29").on('click',function(){
		$("#Preguntas29").next().show();
		$("#Preguntas29").hide();
	});	
	$("#ant28").on('click',function(){
		$("#Preguntas29").prev().show();
		$("#Preguntas29").hide();
	});
	$("#sig30").on('click',function(){
		$("#Preguntas30").next().show();
		$("#Preguntas30").hide();
	});
	$("#ant29").on('click',function(){
		$("#Preguntas30").prev().show();
		$("#Preguntas30").hide();
	});
	$("#sig31").on('click',function(){
		$("#Preguntas31").next().show();
		$("#Preguntas31").hide();
	});	
	$("#ant30").on('click',function(){
		$("#Preguntas31").prev().show();
		$("#Preguntas31").hide();
	});	
	$("#ant31").on('click',function(){
		$("#Preguntas32").prev().show();
		$("#Preguntas32").hide();
	});
	});//fin función ready


/* Función ready RADIOBUTTONS- BARRA DE PROGRESO
	pasa pregunta a pregunta por medio de los radiobuttons
	cambia el color del enlace de la pregunta que se constesta
	oculta el boton enviar y lo muestra al contestar la última pregunta
	cambia el value de progress según la variable de aumento*/
	$(document).ready(function(){//acciona la función ready cuando el documento de carga
		$("#btn").hide();//oculta el boton enviar por su id
		var value=0;//variable de aumento para la barra de progreso
		$("input[name=pregunta1]").click(function(){//asigna la función click al grupo de radiobuttons llamados por su nombre
			$("#p1").css("color","#14BB08");//asigna color al enlace cuando un rb es seleccionado
			value=value+3.125;//aumenta variable cuando un rb es seleccionado
			$("#barraProgreso").val(value);//asignación de variable aumento a la barra de progreso
			$("#Preguntas1").next().show();//muestra el contenedor siguiente al actual llamado por el id del actual
			$("#Preguntas1").hide();//oculta el contenedor actual por su id
		});//fin función click
		$("input[name=pregunta2]").click(function(){
			$("#p2").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas2").next().show();
			$("#Preguntas2").hide();
		});
		$("input[name=pregunta3]").click(function(){
			$("#p3").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas3").next().show();
			$("#Preguntas3").hide();
		});
		$("input[name=pregunta4]").click(function(){
			$("#p4").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas4").next().show();
			$("#Preguntas4").hide();
		});
		$("input[name=pregunta5]").click(function(){
			$("#p5").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas5").next().show();
			$("#Preguntas5").hide();
		});
		$("input[name=pregunta6]").click(function(){
			$("#p6").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas6").next().show();
			$("#Preguntas6").hide();
		});
		$("input[name=pregunta7]").click(function(){
			$("#p7").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas7").next().show();
			$("#Preguntas7").hide();
		});
		$("input[name=pregunta8]").click(function(){
			$("#p8").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas8").next().show();
			$("#Preguntas8").hide();
		});
		$("input[name=pregunta9]").click(function(){
			$("#p9").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas9").next().show();
			$("#Preguntas9").hide();
		});
		$("input[name=pregunta10]").click(function(){
			$("#p10").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas10").next().show();
			$("#Preguntas10").hide();
		});
		$("input[name=pregunta11]").click(function(){
			$("#p11").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas11").next().show();
			$("#Preguntas11").hide();
		});
		$("input[name=pregunta12]").click(function(){
			$("#p12").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas12").next().show();
			$("#Preguntas12").hide();
		});		
		$("input[name=pregunta13]").click(function(){
			$("#p13").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas13").next().show();
			$("#Preguntas13").hide();
		});
		$("input[name=pregunta14]").click(function(){
			$("#p14").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas14").next().show();
			$("#Preguntas14").hide();
		});
		$("input[name=pregunta15]").click(function(){
			$("#p15").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas15").next().show();
			$("#Preguntas15").hide();
		});
		$("input[name=pregunta16]").click(function(){
			$("#p16").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas16").next().show();
			$("#Preguntas16").hide();
			$("#Barra2").show();//muestra el contenedor de la barra de preguntas siguiente por id
			$("#Barra1").hide();//oculta el contenedor de la barra de preguntas actual por id
		});
		$("input[name=pregunta17]").click(function(){
			$("#p17").css("color","#14BB08");value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas17").next().show();
			$("#Preguntas17").hide();
		});
		$("input[name=pregunta18]").click(function(){
			$("#p18").css("color","#14BB08");value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas18").next().show();
			$("#Preguntas18").hide();
		});
		$("input[name=pregunta19]").click(function(){
			$("#p19").css("color","#14BB08");value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas19").next().show();
			$("#Preguntas19").hide();
		});
		$("input[name=pregunta20]").click(function(){
			$("#p20").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas20").next().show();
			$("#Preguntas20").hide();
		});
		$("input[name=pregunta21]").click(function(){
			$("#p21").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas21").next().show();
			$("#Preguntas21").hide();
		});
		$("input[name=pregunta22]").click(function(){
			$("#p22").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas22").next().show();
			$("#Preguntas22").hide();
		});
		$("input[name=pregunta23]").click(function(){
			$("#p23").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas23").next().show();
			$("#Preguntas23").hide();
		});
		$("input[name=pregunta24]").click(function(){
			$("#p24").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas24").next().show();
			$("#Preguntas24").hide();
		});
		$("input[name=pregunta25]").click(function(){
			$("#p25").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas25").next().show();
			$("#Preguntas25").hide();
		});
		$("input[name=pregunta26]").click(function(){
			$("#p26").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas26").next().show();
			$("#Preguntas26").hide();
		});
		$("input[name=pregunta27]").click(function(){
			$("#p27").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas27").next().show();
			$("#Preguntas27").hide();
		});
		$("input[name=pregunta28]").click(function(){
			$("#p28").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas28").next().show();
			$("#Preguntas28").hide();
		});
		$("input[name=pregunta29]").click(function(){
			$("#p29").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas29").next().show();
			$("#Preguntas29").hide();
		});
		$("input[name=pregunta30]").click(function(){
			$("#p30").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas30").next().show();
			$("#Preguntas30").hide();
		});
		$("input[name=pregunta31]").click(function(){
			$("#p31").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#Preguntas31").next().show();
			$("#Preguntas31").hide();
		});
		$("input[name=pregunta32]").click(function(){
			$("#p32").css("color","#14BB08");
			value=value+3.125;
			$("#barraProgreso").val(value);
			$("#btn").show();//muestra el boton enviar por su id
		});
	});//fin función read


/*Función BARRA DE PREGUNTAS
	por medio de enlaces pasa de una pregunta a otra ocultando la actual en pantalla*/
	$(document).ready(function(){//acciona la función ready cuando el documento de carga
		$("#Barra2").hide();//oculta el contenedor de la barra de preguntas según su id
		$("#b1").click(function(){//asigna la función click al enlace según su id para accionar la función
			$("#Barra2").show();//muestra el contenedor de barra de preguntas según su id
			$("#Barra1").hide();//oculta el contenedor de barra de preguntas según su id
		});//fin función click
		$("#b2").click(function(){
			$("#Barra1").show();
			$("#Barra2").hide();
		});
		$("#p1").click(function(){//asigna la función click al enlace según su id para accionar la función
			$("#Preguntas1").show();//muestra el contenedor de barra de preguntas según su id
			$(".Preguntas").hide();//oculta los contenedores de barra de preguntas según su class
		});//fin función click
		$("#p2").click(function(){//asigna la función click al enlace según su id para accionar la función
			$(".Preguntas").hide();//oculta los contenedores de barra de preguntas según su class
			$("#Preguntas2").show();//muestra el contenedor de barra de preguntas según su id
			$(".Preguntas1").hide();//oculta los contenedores de barra de preguntas según su class
		});//fin función click
		$("#p3").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas3").show();
			$(".Preguntas1").hide();
		});
		$("#p4").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas4").show();
			$(".Preguntas1").hide();
		});
		$("#p5").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas5").show();
			$(".Preguntas1").hide();
		});
		$("#p6").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas6").show();
			$(".Preguntas1").hide();
		});
		$("#p7").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas7").show();
			$(".Preguntas1").hide();
		});
		$("#p8").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas8").show();
			$(".Preguntas1").hide();
		});
		$("#p9").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas9").show();
			$(".Preguntas1").hide();
		});
		$("#p10").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas10").show();
			$(".Preguntas1").hide();
		});
		$("#p11").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas11").show();
			$(".Preguntas1").hide();
		});
		$("#p12").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas12").show();
			$(".Preguntas1").hide();
		});
		$("#p13").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas13").show();
			$(".Preguntas1").hide();
		});
		$("#p14").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas14").show();
			$(".Preguntas1").hide();
		});
		$("#p15").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas15").show();
			$(".Preguntas1").hide();
		});
		$("#p16").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas16").show();
			$(".Preguntas1").hide();
		});
		$("#p17").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas17").show();
			$(".Preguntas1").hide();
		});
		$("#p18").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas18").show();
			$(".Preguntas1").hide();
		});
		$("#p19").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas19").show();
			$(".Preguntas1").hide();
		});
		$("#p20").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas20").show();
			$(".Preguntas1").hide();
		});
		$("#p21").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas21").show();
			$(".Preguntas1").hide();
		});
		$("#p22").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas22").show();
			$(".Preguntas1").hide();
		});
		$("#p23").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas23").show();
			$(".Preguntas1").hide();
		});
		$("#p24").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas24").show();
			$(".Preguntas1").hide();
		});
		$("#p25").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas25").show();
			$(".Preguntas1").hide();
		});
		$("#p26").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas26").show();
			$(".Preguntas1").hide();
		});
		$("#p27").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas27").show();
			$(".Preguntas1").hide();
		});
		$("#p28").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas28").show();
			$(".Preguntas1").hide();
		});
		$("#p29").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas29").show();
			$(".Preguntas1").hide();
		});
		$("#p30").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas30").show();
			$(".Preguntas1").hide();
		});
		$("#p31").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas31").show();
			$(".Preguntas1").hide();
		});
		$("#p32").click(function(){
			$(".Preguntas").hide();
			$("#Preguntas32").show();
			$(".Preguntas1").hide();
		});
	});//fin función ready

}